import NRR.OddSphereDegree.AlgebraicTopology.SmallSimplices

/-!
# The subcomplex of `𝒰`-small singular chains

For an open cover `𝒰` of a space `X`, this file defines, in each degree `n`, the
`R`-submodule

```text
C_n^𝒰(X; R) ⊆ C_n(X; R)
```

of the singular chain group generated by the basis chains `chainGenerator R X n σ`
of the `𝒰`-small singular simplices `σ` (those whose image lies in one member of
the cover, in the sense of `SphereOddDegree.IsSmallSimplex`).

We prove:

* `SphereOddDegree.chainGenerator_mem_smallChainSubmodule` — each small generator
 lies in the submodule;
* `SphereOddDegree.smallChainSubmodule_induction` — an induction/elimination
 principle for membership in the submodule;
* `SphereOddDegree.singularBoundary_maps_smallChainSubmodule` — the singular
 boundary maps small chains to small chains.

The boundary stability uses the singular boundary generator formula from the
operator file (`singularBoundary_chainGenerator_formula`) and the face-smallness
lemma `IsSmallSimplex.face` from the small-simplex file. Together these results
are exactly what is needed to assemble the small singular chains into a
subcomplex of the singular chain complex.
-/

open CategoryTheory AlgebraicTopology
open SphereOddDegree.AffineBarycentricSubdivision

namespace SphereOddDegree

variable {R : Type} [CommRing R] {X : TopCat.{0}}

/-! ## 1. The small-chain submodule -/

/-- The `R`-submodule `C_n^𝒰(X; R) ⊆ C_n(X; R)` of singular chains generated by
the basis chains `chainGenerator R X n σ` for `𝒰`-small singular simplices `σ`. -/
noncomputable def smallChainSubmodule
    (R : Type) [CommRing R] (X : TopCat.{0})
    (𝒰 : OpenCoverData X) (n : ℕ) :
    Submodule R (singularChainGroup R X n) :=
  Submodule.span R
    {c | ∃ σ : singularSimplices X n, IsSmallSimplex 𝒰 σ ∧ chainGenerator R X n σ = c}

/-- Each small generator lies in the small-chain submodule. -/
theorem chainGenerator_mem_smallChainSubmodule
    {𝒰 : OpenCoverData X} {n : ℕ} {σ : singularSimplices X n}
    (hσ : IsSmallSimplex 𝒰 σ) :
    chainGenerator R X n σ ∈ smallChainSubmodule R X 𝒰 n :=
  Submodule.subset_span ⟨σ, hσ, rfl⟩

/-- **Induction principle for the small-chain submodule.** To prove a property
`p` of every chain in `smallChainSubmodule R X 𝒰 n`, it suffices to prove it for
the small generators and check that it is preserved under `0`, addition and
scalar multiplication. -/
theorem smallChainSubmodule_induction
    {𝒰 : OpenCoverData X} {n : ℕ}
    {p : singularChainGroup R X n → Prop}
    (mem : ∀ σ : singularSimplices X n, IsSmallSimplex 𝒰 σ → p (chainGenerator R X n σ))
    (zero : p 0)
    (add : ∀ x y, p x → p y → p (x + y))
    (smul : ∀ (a : R) x, p x → p (a • x))
    {c : singularChainGroup R X n} (hc : c ∈ smallChainSubmodule R X 𝒰 n) :
    p c := by
  refine Submodule.span_induction (p := fun x _ => p x) ?_ zero ?_ ?_ hc
  · rintro x ⟨σ, hσ, rfl⟩
    exact mem σ hσ
  · intro x y _ _ hx hy
    exact add x y hx hy
  · intro a x _ hx
    exact smul a x hx

/-! ## 2. Boundary stability -/

/-- **Boundary stability.** The singular boundary maps the submodule of small
`(n+1)`-chains into the submodule of small `n`-chains. -/
theorem singularBoundary_maps_smallChainSubmodule
    {𝒰 : OpenCoverData X} (n : ℕ) :
    ∀ c ∈ smallChainSubmodule R X 𝒰 (n + 1),
      (singularBoundary R X n).hom c ∈ smallChainSubmodule R X 𝒰 n := by
  intro c hc
  have hle : smallChainSubmodule R X 𝒰 (n + 1)
      ≤ Submodule.comap (singularBoundary R X n).hom (smallChainSubmodule R X 𝒰 n) := by
    rw [smallChainSubmodule, Submodule.span_le]
    rintro _ ⟨σ, hσ, rfl⟩
    rw [SetLike.mem_coe, Submodule.mem_comap, singularBoundary_chainGenerator_formula]
    refine Submodule.sum_mem _ ?_
    intro i _
    refine Submodule.smul_mem _ _ ?_
    exact chainGenerator_mem_smallChainSubmodule (hσ.face i)
  exact hle hc

end SphereOddDegree
