import NRR.OddSphereDegree.AlgebraicTopology.SmallChainComplex
import Mathlib

/-!
# Subordinate singular chains for a single subset

For a topological space `X` and a subset `S ⊆ X`, this file defines, in each
degree `n`, the `R`-submodule

```text
C_n^S(X; R) ⊆ C_n(X; R)
```

of singular chains generated by the basis chains `chainGenerator R X n σ` of the
singular simplices `σ` whose image lies entirely in `S` (`IsSubordinate S σ`).
These submodules assemble into a chain complex `subChainComplex R X S`, and we
provide the inclusion chain maps between subordinate complexes for `S ⊆ T`, and
into the small-chain complex when `S` is a member of an open cover.

This is the algebraic backbone of singular Mayer–Vietoris: for an open cover
`{U, V}` of `X`, the complexes `subChainComplex R X ↑U`, `subChainComplex R X ↑V`
and `subChainComplex R X (↑U ∩ ↑V)` are the singular chains supported in `U`,
`V` and `U ∩ V` respectively.
-/

open CategoryTheory AlgebraicTopology
open SphereOddDegree.AffineBarycentricSubdivision

namespace SphereOddDegree

variable {R : Type} [CommRing R] {X : TopCat.{0}}

/-! ## 1. Subordinate simplices -/

/-- A singular `n`-simplex `σ` is **subordinate to** the subset `S ⊆ X` if its
image is contained in `S`. -/
def IsSubordinate (S : Set X) {n : ℕ} (σ : singularSimplices X n) : Prop :=
  Set.range (mvSimplexMap σ) ⊆ S

/-- Subordination is monotone in the set. -/
theorem IsSubordinate.mono {S T : Set X} {n : ℕ} {σ : singularSimplices X n}
    (hσ : IsSubordinate S σ) (h : S ⊆ T) : IsSubordinate T σ :=
  hσ.trans h

/-- Subordination is inherited along a factorization of the underlying maps. -/
theorem IsSubordinate.comp_of_range_subset {S : Set X} {m n : ℕ}
    {σ : singularSimplices X n} {τ : singularSimplices X m}
    (φ : C(Delta m, Delta n))
    (hcomp : mvSimplexMap τ = (mvSimplexMap σ).comp φ)
    (hσ : IsSubordinate S σ) :
    IsSubordinate S τ := by
  refine (?_ : Set.range (mvSimplexMap τ) ⊆ Set.range (mvSimplexMap σ)).trans hσ
  rw [hcomp]
  rintro _ ⟨y, rfl⟩
  exact ⟨φ y, rfl⟩

/-- **Face stability.** Every boundary face of a subordinate simplex is
subordinate (a face has image contained in the image of the original simplex). -/
theorem IsSubordinate.face {S : Set X} {n : ℕ}
    {σ : singularSimplices X (n + 1)} (hσ : IsSubordinate S σ) (i : Fin (n + 2)) :
    IsSubordinate S (AlexanderWhitney.faceSimplex X n i σ) :=
  hσ.comp_of_range_subset (cofaceTop n i) (faceSimplex_continuousMap X n i σ)

/-- If `σ` is subordinate to a member `S` of an open cover `𝒰`, then `σ` is
`𝒰`-small. -/
theorem IsSubordinate.isSmallSimplex {𝒰 : OpenCoverData X} {S : Set X}
    (hS : S ∈ 𝒰.sets) {n : ℕ} {σ : singularSimplices X n}
    (hσ : IsSubordinate S σ) : IsSmallSimplex 𝒰 σ :=
  ⟨S, hS, hσ⟩

/-! ## 2. The subordinate-chain submodule -/

/-- The `R`-submodule `C_n^S(X; R) ⊆ C_n(X; R)` of singular chains generated by
the basis chains `chainGenerator R X n σ` for simplices `σ` subordinate to `S`. -/
noncomputable def subChainSubmodule
    (R : Type) [CommRing R] (X : TopCat.{0}) (S : Set X) (n : ℕ) :
    Submodule R (singularChainGroup R X n) :=
  Submodule.span R
    {c | ∃ σ : singularSimplices X n, IsSubordinate S σ ∧ chainGenerator R X n σ = c}

/-- Each subordinate generator lies in the subordinate-chain submodule. -/
theorem chainGenerator_mem_subChainSubmodule
    {S : Set X} {n : ℕ} {σ : singularSimplices X n}
    (hσ : IsSubordinate S σ) :
    chainGenerator R X n σ ∈ subChainSubmodule R X S n :=
  Submodule.subset_span ⟨σ, hσ, rfl⟩

/-- **Induction principle for the subordinate-chain submodule.** -/
theorem subChainSubmodule_induction
    {S : Set X} {n : ℕ}
    {p : singularChainGroup R X n → Prop}
    (mem : ∀ σ : singularSimplices X n, IsSubordinate S σ → p (chainGenerator R X n σ))
    (zero : p 0)
    (add : ∀ x y, p x → p y → p (x + y))
    (smul : ∀ (a : R) x, p x → p (a • x))
    {c : singularChainGroup R X n} (hc : c ∈ subChainSubmodule R X S n) :
    p c := by
  refine Submodule.span_induction (p := fun x _ => p x) ?_ zero ?_ ?_ hc
  · rintro x ⟨σ, hσ, rfl⟩
    exact mem σ hσ
  · intro x y _ _ hx hy
    exact add x y hx hy
  · intro a x _ hx
    exact smul a x hx

/-- The subordinate-chain submodules are monotone in the set. -/
theorem subChainSubmodule_mono {S T : Set X} (h : S ⊆ T) (n : ℕ) :
    subChainSubmodule R X S n ≤ subChainSubmodule R X T n := by
  apply Submodule.span_mono
  rintro _ ⟨σ, hσ, rfl⟩
  exact ⟨σ, hσ.mono h, rfl⟩

/-- If `S` is a member of the open cover `𝒰`, the subordinate chains for `S` are
contained in the `𝒰`-small chains. -/
theorem subChainSubmodule_le_smallChainSubmodule {𝒰 : OpenCoverData X} {S : Set X}
    (hS : S ∈ 𝒰.sets) (n : ℕ) :
    subChainSubmodule R X S n ≤ smallChainSubmodule R X 𝒰 n := by
  apply Submodule.span_mono
  rintro _ ⟨σ, hσ, rfl⟩
  exact ⟨σ, hσ.isSmallSimplex hS, rfl⟩

/-! ## 3. Boundary stability -/

/-- **Boundary stability.** The singular boundary maps the submodule of
subordinate `(n+1)`-chains into the submodule of subordinate `n`-chains. -/
theorem singularBoundary_maps_subChainSubmodule
    {S : Set X} (n : ℕ) :
    ∀ c ∈ subChainSubmodule R X S (n + 1),
      (singularBoundary R X n).hom c ∈ subChainSubmodule R X S n := by
  intro c hc
  have hle : subChainSubmodule R X S (n + 1)
      ≤ Submodule.comap (singularBoundary R X n).hom (subChainSubmodule R X S n) := by
    rw [subChainSubmodule, Submodule.span_le]
    rintro _ ⟨σ, hσ, rfl⟩
    rw [SetLike.mem_coe, Submodule.mem_comap, singularBoundary_chainGenerator_formula]
    refine Submodule.sum_mem _ ?_
    intro i _
    refine Submodule.smul_mem _ _ ?_
    exact chainGenerator_mem_subChainSubmodule (hσ.face i)
  exact hle hc

/-! ## 4. The subordinate-chain complex -/

/-- The restriction of the singular boundary to the subordinate-chain
submodules. -/
noncomputable def subBoundary (R : Type) [CommRing R] (X : TopCat.{0})
    (S : Set X) (n : ℕ) :
    ModuleCat.of R (subChainSubmodule R X S (n + 1)) ⟶
      ModuleCat.of R (subChainSubmodule R X S n) :=
  ModuleCat.ofHom
    ((singularBoundary R X n).hom.restrict (singularBoundary_maps_subChainSubmodule n))

@[simp] theorem subBoundary_hom_apply
    {S : Set X} (n : ℕ) (c : subChainSubmodule R X S (n + 1)) :
    ((subBoundary R X S n).hom c : singularChainGroup R X n)
      = (singularBoundary R X n).hom (c : singularChainGroup R X (n + 1)) :=
  rfl

theorem subBoundary_comp_subBoundary
    {S : Set X} (n : ℕ) :
    subBoundary R X S (n + 1) ≫ subBoundary R X S n = 0 := by
  ext c
  simp +decide [subBoundary]
  convert congr_arg (fun f => f c.val)
    ((singularChainComplex R X).d_comp_d (n + 2) (n + 1) n) using 1

/-- **The subordinate-chain complex** `C_*^S(X; R)`. -/
noncomputable def subChainComplex (R : Type) [CommRing R] (X : TopCat.{0})
    (S : Set X) : ChainComplex (ModuleCat.{0} R) ℕ :=
  ChainComplex.of (fun n => ModuleCat.of R (subChainSubmodule R X S n))
    (fun n => subBoundary R X S n)
    (fun n => subBoundary_comp_subBoundary n)

@[simp] theorem subChainComplex_X
    {S : Set X} (n : ℕ) :
    (subChainComplex R X S).X n = ModuleCat.of R (subChainSubmodule R X S n) :=
  rfl

@[simp] theorem subChainComplex_d
    {S : Set X} (n : ℕ) :
    (subChainComplex R X S).d (n + 1) n = subBoundary R X S n :=
  ChainComplex.of_d _ _ _ n

/-! ## 5. Inclusion chain maps -/

/-- The inclusion chain map `C_*^S(X; R) ⟶ C_*^T(X; R)` for `S ⊆ T`. -/
noncomputable def subChainInclusion (S T : Set X) (h : S ⊆ T) :
    subChainComplex R X S ⟶ subChainComplex R X T where
  f n := ModuleCat.ofHom (Submodule.inclusion (subChainSubmodule_mono h n))
  comm' i j hij := by
    obtain ⟨k, hk⟩ := hij
    ext c
    apply Subtype.ext
    simp +decide [subChainComplex, subBoundary, Submodule.inclusion]

@[simp] theorem subChainInclusion_f_apply
    {S T : Set X} (h : S ⊆ T) (n : ℕ) (c : subChainSubmodule R X S n) :
    (((subChainInclusion S T h).f n).hom c).val = (c : singularChainGroup R X n) :=
  rfl

/-- The inclusion chain map `C_*^S(X; R) ⟶ C_*^𝒰(X; R)` of the subordinate chains
for a cover member `S` into the small-chain complex. -/
noncomputable def subChainToSmall (𝒰 : OpenCoverData X) (S : Set X) (hS : S ∈ 𝒰.sets) :
    subChainComplex R X S ⟶ smallChainComplex R X 𝒰 where
  f n := ModuleCat.ofHom (Submodule.inclusion (subChainSubmodule_le_smallChainSubmodule hS n))
  comm' i j hij := by
    obtain ⟨k, hk⟩ := hij
    ext c
    apply Subtype.ext
    simp +decide [subChainComplex, smallChainComplex, subBoundary, smallBoundary,
      Submodule.inclusion]

@[simp] theorem subChainToSmall_f_apply
    {𝒰 : OpenCoverData X} {S : Set X} (hS : S ∈ 𝒰.sets) (n : ℕ)
    (c : subChainSubmodule R X S n) :
    (((subChainToSmall 𝒰 S hS).f n).hom c).val = (c : singularChainGroup R X n) :=
  rfl

end SphereOddDegree
