import Mathlib.Data.Nat.Factors
import NRR.PrimeRefinement.Core
import NRR.PrimeRefinement.IndexedPartition
import NRR.BodySpace.FullBody
import NRR.Multivalued.PerimeterObservable

set_option backward.isDefEq.respectTransparency false

/-!
# Iteration of the prime-refinement lemma

Assuming `PrimeRefinementTheorem`, this module performs the complete formal iteration over a list
of prime factors, flattens the resulting nested power partitions, and derives the arbitrary-number
fair-partition theorem.  The construction is parameterized by the prime-refinement separator theorem.
-/

open MeasureTheory

namespace NRR

open Geometry

/-- A natural number equipped with a proof of primality. -/
abbrev PrimeFactor := {p : ℕ // Nat.Prime p}

/-- Product of a list of prime factors. -/
def primeFactorProduct (ps : List PrimeFactor) : ℕ :=
  (ps.map Subtype.val).prod

/-- The nested finite index type generated by successive prime refinements. -/
def PrimeRefinementIndex : List PrimeFactor → Type
  | [] => Unit
  | p :: ps => Fin p.1 × PrimeRefinementIndex ps

noncomputable instance primeRefinementIndexFintype :
    (ps : List PrimeFactor) → Fintype (PrimeRefinementIndex ps)
  | [] => (inferInstance : Fintype Unit)
  | p :: ps =>
      letI := primeRefinementIndexFintype ps
      (inferInstance : Fintype (Fin p.1 × PrimeRefinementIndex ps))

@[simp] theorem card_primeRefinementIndex (ps : List PrimeFactor) :
    Fintype.card (PrimeRefinementIndex ps) = primeFactorProduct ps := by
  induction ps with
  | nil => simp [PrimeRefinementIndex, primeFactorProduct]
  | cons p ps ih =>
      letI := primeRefinementIndexFintype ps
      show Fintype.card (Fin p.1 × PrimeRefinementIndex ps) =
        primeFactorProduct (p :: ps)
      rw [Fintype.card_prod, Fintype.card_fin, ih]
      simp [primeFactorProduct]

/-- Repeatedly divide an area threshold by the listed primes. -/
noncomputable def primeDescendArea (A : ℝ) : List PrimeFactor → ℝ
  | [] => A
  | p :: ps => primeDescendArea (A / (p.1 : ℝ)) ps

/-- Repeated prime descent preserves positivity. -/
theorem primeDescendArea_pos
    {A : ℝ} (hA : 0 < A) :
    ∀ ps : List PrimeFactor, 0 < primeDescendArea A ps
  | [] => hA
  | p :: ps =>
      primeDescendArea_pos
        (div_pos hA (by exact_mod_cast p.2.pos)) ps

/-- The prime factors of a positive natural number, bundled with primality proofs. -/
def bundledPrimeFactors (n : ℕ) : List PrimeFactor :=
  n.primeFactorsList.attach.map
    (fun p => ⟨p.1, Nat.prime_of_mem_primeFactorsList p.2⟩)

@[simp] theorem primeFactorProduct_bundledPrimeFactors
    {n : ℕ} (hn : n ≠ 0) :
    primeFactorProduct (bundledPrimeFactors n) = n := by
  simp [primeFactorProduct, bundledPrimeFactors, Nat.prod_primeFactorsList hn]

/-- The flattened partition data decoded from an iterated refined zero. -/
structure IteratedPartitionWitness
    {K : Geometry.ConvexBody Plane}
    (ps : List PrimeFactor) (A : ℝ) (hA : 0 < A)
    (φ : NiceMV (BodySpace K (primeDescendArea A ps)))
    (C : BodySpace K A) (y : SignedInterval) where
  partition :
    IndexedConvexPartition
      (EMP.VariableBody.solidBody hA C)
      (PrimeRefinementIndex ps)
  leaf : PrimeRefinementIndex ps → BodySpace K (primeDescendArea A ps)
  piece_eq_leaf :
    ∀ i, (partition.piece i : Set Plane) = ((leaf i).body : Set Plane)
  piece_area_eq :
    ∀ i, (partition.piece i).area = primeDescendArea C.body.area ps
  leaf_zero : ∀ i, φ.Zero (leaf i) y

/-- A nice multivalued function obtained by iterating prime refinement, together with the decoder
from each output zero to the flattened partition witness. -/
structure IteratedRefinement
    {K : Geometry.ConvexBody Plane}
    (ps : List PrimeFactor) (A : ℝ) (hA : 0 < A)
    (φ : NiceMV (BodySpace K (primeDescendArea A ps))) where
  output : NiceMV (BodySpace K A)
  decode :
    ∀ C : BodySpace K A, ∀ y : SignedInterval,
      output.Zero C y → IteratedPartitionWitness ps A hA φ C y

namespace IteratedRefinement

/-- Build the full iterated refinement from the prime-refinement separator theorem. -/
noncomputable def build
    {K : Geometry.ConvexBody Plane}
    (H : PrimeRefinementTheorem) :
    (ps : List PrimeFactor) →
    (A : ℝ) → (hA : 0 < A) → (hAK : A ≤ K.area) →
    (φ : NiceMV (BodySpace K (primeDescendArea A ps))) →
    IteratedRefinement ps A hA φ
  | [], A, hA, hAK, φ =>
      { output := φ
        decode := by
          intro C y hy
          exact
            { partition := IndexedConvexPartition.singleton
                (EMP.VariableBody.solidBody hA C)
              leaf := fun _ => C
              piece_eq_leaf := fun _ => rfl
              piece_area_eq := fun _ => rfl
              leaf_zero := fun _ => hy } }
  | p :: ps, A, hA, hAK, φ => by
      have hpA : 0 < A / (p.1 : ℝ) :=
        div_pos hA (by exact_mod_cast p.2.pos)
      have hpOne : (1 : ℝ) ≤ (p.1 : ℝ) := by
        exact_mod_cast p.2.one_le
      have hpAK : A / (p.1 : ℝ) ≤ K.area :=
        (div_le_self (le_of_lt hA) hpOne).trans hAK
      let inner := build H ps (A / (p.1 : ℝ)) hpA hpAK φ
      letI : Nonempty (BodySpace K A) :=
        ⟨BodySpace.parentAt K hAK⟩
      let S := Classical.choice (H p.1 p.2 K A hA inner.output)
      exact
        { output := S.toNiceMV
          decode := by
            intro C y hy
            have hlift := S.zero_lifts_to_all_children hy
            let x := hlift.choose
            have hx : ∀ i : Fin p.1,
                inner.output.Zero
                  (EMP.VariableBody.child
                    (foxNeuwirthTopCellModel p.2).sites hA p.2.pos (C, x) i) y := by
              intro i
              change inner.output.Zero
                (EMP.VariableBody.child
                  (foxNeuwirthTopCellModel p.2).sites hA p.2.pos
                    (C, hlift.choose) i) y
              exact hlift.choose_spec i
            let W := EMP.VariableBody.witness
              (foxNeuwirthTopCellModel p.2).sites hA p.2.pos (C, x)
            let R : ∀ i : Fin p.1,
                IteratedPartitionWitness ps (A / (p.1 : ℝ)) hpA φ (W.child i) y :=
              fun i => inner.decode (W.child i) y (by
                simpa [W, EMP.VariableBody.witness] using hx i)
            refine
              { partition :=
                  { piece := fun ij => (R ij.1).partition.piece ij.2
                    subset := by
                      rintro ⟨i, j⟩ z hz
                      apply W.partition.subset i
                      rw [W.piece_eq i]
                      simpa only [EMP.VariableBody.solidBody_carrier] using
                        (R i).partition.subset j hz
                    covers := by
                      intro z hz
                      obtain ⟨i, hi⟩ := Set.mem_iUnion.mp (W.covers hz)
                      have hchild : z ∈
                          (EMP.VariableBody.solidBody hpA (W.child i) : Set Plane) := by
                        simpa only [EMP.VariableBody.solidBody_carrier] using
                          (show z ∈ ((W.child i).body : Set Plane) by
                            rw [← W.piece_eq i]
                            exact hi)
                      obtain ⟨j, hj⟩ :=
                        Set.mem_iUnion.mp ((R i).partition.covers hchild)
                      exact Set.mem_iUnion.mpr ⟨(i, j), hj⟩
                    nullOverlap := by
                      rintro ⟨i, a⟩ ⟨j, b⟩ hij
                      by_cases hfirst : i = j
                      · subst j
                        apply (R i).partition.nullOverlap a b
                        intro hab
                        apply hij
                        exact congrArg (fun t => (i, t)) hab
                      · apply measure_mono_null ?_ (W.nullOverlap i j hfirst)
                        rintro z ⟨hza, hzb⟩
                        constructor
                        · rw [W.piece_eq i]
                          simpa only [EMP.VariableBody.solidBody_carrier] using
                            (R i).partition.subset a hza
                        · rw [W.piece_eq j]
                          simpa only [EMP.VariableBody.solidBody_carrier] using
                            (R j).partition.subset b hzb }
                leaf := fun ij => (R ij.1).leaf ij.2
                piece_eq_leaf := by
                  rintro ⟨i, j⟩
                  exact (R i).piece_eq_leaf j
                piece_area_eq := by
                  rintro ⟨i, j⟩
                  rw [(R i).piece_area_eq j]
                  have hchildArea :
                      (W.child i).body.area = C.body.area / (p.1 : ℝ) := by
                    simpa [W, EMP.VariableBody.witness] using
                      EMP.VariableBody.child_area_eq
                        (foxNeuwirthTopCellModel p.2).sites hA p.2.pos (C, x) i
                  simp [primeDescendArea, hchildArea]
                leaf_zero := by
                  rintro ⟨i, j⟩
                  exact (R i).leaf_zero j }
        }

end IteratedRefinement

namespace IteratedPartitionWitness

variable {K : Geometry.ConvexBody Plane}
variable {ps : List PrimeFactor} {A : ℝ} {hA : 0 < A}
variable {φ : NiceMV (BodySpace K (primeDescendArea A ps))}
variable {C : BodySpace K A} {y : SignedInterval}

/-- The decoded flattened partition has equal area. -/
theorem partition_isEqualArea
    (W : IteratedPartitionWitness ps A hA φ C y) :
    W.partition.IsEqualArea := by
  intro i j
  rw [W.piece_area_eq i, W.piece_area_eq j]

/-- When the leaf function is the normalized perimeter observable, all flattened pieces have equal
perimeter because every leaf is a zero at the same signed parameter. -/
theorem partition_hasEqualPerimeter
    (W : IteratedPartitionWitness ps A hA
      (perimeterNiceMV K (primeDescendArea A ps) (primeDescendArea_pos hA ps)) C y) :
    W.partition.HasEqualPerimeter := by
  intro i j
  have hzi :=
    (perimeterNiceMV_zero_iff (primeDescendArea_pos hA ps) (W.leaf i) y).mp
      (W.leaf_zero i)
  have hzj :=
    (perimeterNiceMV_zero_iff (primeDescendArea_pos hA ps) (W.leaf j) y).mp
      (W.leaf_zero j)
  have hnorm :
      normalizedPerimeter K (primeDescendArea A ps) (primeDescendArea_pos hA ps)
          (W.leaf i) =
        normalizedPerimeter K (primeDescendArea A ps) (primeDescendArea_pos hA ps)
          (W.leaf j) :=
    hzi.symm.trans hzj
  simp only [normalizedPerimeter_apply] at hnorm
  have hden : 1 + K.perimeter ≠ 0 :=
    ne_of_gt (one_add_perimeter_pos K)
  field_simp [hden] at hnorm
  have hpiece_i :
      W.partition.piece i =
        (W.leaf i).toGeometryConvexBody (primeDescendArea_pos hA ps) :=
    Geometry.ConvexBody.ext (W.piece_eq_leaf i)
  have hpiece_j :
      W.partition.piece j =
        (W.leaf j).toGeometryConvexBody (primeDescendArea_pos hA ps) :=
    Geometry.ConvexBody.ext (W.piece_eq_leaf j)
  rw [hpiece_i, hpiece_j]
  exact hnorm

end IteratedPartitionWitness

/-- **Arbitrary-number AAK theorem from the prime-refinement separator theorem.** -/
theorem exists_fair_partition_of_primeRefinement
    (H : PrimeRefinementTheorem)
    (K : Geometry.ConvexBody Plane) (n : ℕ) (hn : 0 < n) :
    ∃ P : ConvexPartition K n, P.IsFair := by
  have hKpos : 0 < K.area := (SolidConvexBody.ofConvexBody K).area_pos
  let ps := bundledPrimeFactors n
  have hn0 : n ≠ 0 := Nat.ne_of_gt hn
  have hprod : primeFactorProduct ps = n := by
    simpa [ps] using primeFactorProduct_bundledPrimeFactors hn0
  have hbase : 0 < primeDescendArea K.area ps :=
    primeDescendArea_pos hKpos ps
  let φ := perimeterNiceMV K (primeDescendArea K.area ps) hbase
  let R := IteratedRefinement.build H ps K.area hKpos le_rfl φ
  let C : BodySpace K K.area := BodySpace.full K
  obtain ⟨y, hy⟩ := R.output.exists_zero C
  let W := R.decode C y hy
  have hparent : EMP.VariableBody.solidBody hKpos C = K := by
    simpa [C, EMP.VariableBody.solidBody] using
      BodySpace.toGeometryConvexBody_full K hKpos
  let PI : IndexedConvexPartition K (PrimeRefinementIndex ps) :=
    W.partition.castBody hparent
  have hPIarea : PI.IsEqualArea :=
    (IndexedConvexPartition.castBody_isEqualArea hparent W.partition).2
      W.partition_isEqualArea
  have hPIperimeter : PI.HasEqualPerimeter :=
    (IndexedConvexPartition.castBody_hasEqualPerimeter hparent W.partition).2
      W.partition_hasEqualPerimeter
  rw [← hprod, ← card_primeRefinementIndex ps]
  refine ⟨PI.toConvexPartition, ?_⟩
  exact ⟨PI.toConvexPartition_isEqualArea hPIarea,
    PI.toConvexPartition_hasEqualPerimeter hPIperimeter⟩

/-- Public implication form of the Avvakumov--Akopyan--Karasev theorem.  The conclusion for every
positive number of pieces follows formally from the single prime-refinement separator theorem. -/
theorem avvakumov_akopyan_karasev_of_primeRefinement
    (H : PrimeRefinementTheorem) :
    ∀ (K : Geometry.ConvexBody Plane) (n : ℕ), 0 < n →
      ∃ P : ConvexPartition K n, P.IsFair := by
  intro K n hn
  exact exists_fair_partition_of_primeRefinement H K n hn

end NRR
