import NRR.PrimePolyhedron.FoxNeuwirth.RouteBBadSetNullity
import Mathlib.MeasureTheory.Measure.Prod

/-!
# Route B: vector-fiber elimination of the barycentric witness

The scalar-fiber argument of Step 4 is insufficient after existentially
quantifying over barycentric witnesses.  The correct fiber is the complete
`p`-vector attached to one retained movable vertex.

Fix all other vertex values.  If the selected vertex has positive barycentric
weight and the affine face value lies on the diagonal line, then its vector is
contained in the affine set generated by

* the remaining `p - 2` retained face vertices, and
* the diagonal direction `1`.

This affine set has dimension at most `(p - 2) + 1 = p - 1` in `Real^p`, and
therefore has zero `p`-dimensional Lebesgue measure.  Fubini then gives nullity
of the complete bad parameter set.

The definitions below isolate this argument independently of the collar's
coordinate bookkeeping.  The only collar-specific obligation left after this
file is to exhibit the `p` independent movable scalar orbits forming the value
of the selected local vertex and the corresponding product-coordinate split.
-/

namespace NRR

open MeasureTheory
open scoped BigOperators

namespace FoxNeuwirthOrderComplex
namespace EquivariantPrismStableRelativeBoundary
namespace ExplicitAffineRelativeCollar
namespace RouteB

open Parameters
open RelativeGenericity
open EquivariantPrismGenericPerturbation

/-- A product set whose every vector fiber is null is null.  This is the exact
Fubini step needed by the vector-block argument. -/
theorem volume_prod_eq_zero_of_fiberwise_eq_zero
    {X Y : Type*}
    [MeasurableSpace X] [MeasurableSpace Y]
    (μ : Measure X) (ν : Measure Y)
    [SFinite μ] [SFinite ν]
    (s : Set (X × Y))
    (hs : MeasurableSet s)
    (hfiber : ∀ x, ν {y | (x, y) ∈ s} = 0) :
    (μ.prod ν) s = 0 := by
  rw [Measure.prod_apply hs]
  have hfiber' : (fun x => ν (Prod.mk x ⁻¹' s)) = 0 := by
    funext x
    exact hfiber x
  rw [hfiber']
  exact lintegral_zero

/-- Abstract data for a full vector-block elimination.

`Rest` represents all movable parameters except the `p` scalar coordinates of
one selected vertex value.  `badInSplitCoordinates` is the complete bad set in
those product coordinates, including the existential barycentric witness.
The substantive geometric field is `fiber_null`: unlike the old scalar
statement, it already quantifies over every barycentric witness. -/
structure VectorBlockEliminationData (p : Nat) where
  Rest : Type*
  [instMeasureSpaceRest : MeasureSpace Rest]
  [instSFiniteVolumeRest : SFinite (volume : Measure Rest)]
  badInSplitCoordinates : Set (Rest × (Fin p → Real))
  measurable_bad : MeasurableSet badInSplitCoordinates
  fiber_null : ∀ rest,
    volume {u : Fin p → Real | (rest, u) ∈ badInSplitCoordinates} = 0

attribute [instance]
  VectorBlockEliminationData.instMeasureSpaceRest
  VectorBlockEliminationData.instSFiniteVolumeRest

/-- Vector-fiber elimination removes the uncountable barycentric witness by
Fubini. -/
theorem VectorBlockEliminationData.volume_bad_eq_zero
    {p : Nat} (D : VectorBlockEliminationData p) :
    ((volume : Measure D.Rest).prod volume) D.badInSplitCoordinates = 0 := by
  letI : MeasureSpace D.Rest := D.instMeasureSpaceRest
  letI : SFinite (volume : Measure D.Rest) := D.instSFiniteVolumeRest
  exact volume_prod_eq_zero_of_fiberwise_eq_zero
    (volume : Measure D.Rest) volume D.badInSplitCoordinates
    D.measurable_bad D.fiber_null

/-- Collar-specific coordinate transport certificate.

The image equality says that the complete mixed-face bad set, after splitting
movable parameters into all remaining coordinates and the selected vertex's
full value, is exactly `D.badInSplitCoordinates`.  `measure_transport` records
that this finite coordinate permutation preserves Lebesgue measure. -/
structure MixedFaceVectorBlockCertificate
    {p N₀ N₁ M L : Nat}
    (hp : Nat.Prime p)
    (C : RelativeAffineCellSystem hp N₀ N₁ M L)
    (base : Assignment hp C)
    (κ : MixedFaceCase hp C) where
  data : VectorBlockEliminationData p
  split : MovableParameterSpace hp C → data.Rest × (Fin p → Real)
  bad_image : split '' mixedFaceBadSet hp C base κ = data.badInSplitCoordinates
  measure_transport :
    volume (mixedFaceBadSet hp C base κ) =
      ((volume : Measure data.Rest).prod volume) data.badInSplitCoordinates

/-- A full vector-block certificate solves the Step 5 elimination subproblem. -/
theorem hasNullElimination_of_vectorBlockCertificate
    {p N₀ N₁ M L : Nat}
    (hp : Nat.Prime p)
    (C : RelativeAffineCellSystem hp N₀ N₁ M L)
    (base : Assignment hp C)
    (κ : MixedFaceCase hp C)
    (D : MixedFaceVectorBlockCertificate hp C base κ) :
    HasNullElimination hp C base κ := by
  change volume (mixedFaceBadSet hp C base κ) = 0
  rw [D.measure_transport]
  exact D.data.volume_bad_eq_zero

/-- Simultaneous perturbation follows once every finite mixed-face case is
supplied with its vector-block coordinate certificate. -/
theorem exists_mem_ball_avoiding_all_of_vectorBlockCertificates
    {p N₀ N₁ M L : Nat}
    (hp : Nat.Prime p)
    (C : RelativeAffineCellSystem hp N₀ N₁ M L)
    (base : Assignment hp C)
    (center : MovableParameterSpace hp C)
    (radius : Real)
    (hball : volume (Metric.ball center radius) ≠ 0)
    (hcert : ∀ κ : MixedFaceCase hp C,
      MixedFaceVectorBlockCertificate hp C base κ) :
    ∃ x ∈ Metric.ball center radius,
      ∀ κ : MixedFaceCase hp C, x ∉ mixedFaceBadSet hp C base κ := by
  apply exists_mem_ball_avoiding_all_mixedFaceBadSets hp C base center radius hball
  intro κ
  apply certificate_of_hasNullElimination hp C base κ
  exact hasNullElimination_of_vectorBlockCertificate hp C base κ (hcert κ)

end RouteB
end ExplicitAffineRelativeCollar
end EquivariantPrismStableRelativeBoundary
end FoxNeuwirthOrderComplex
end NRR
